# Generated by Django 3.2.5 on 2021-07-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('father_name', models.TextField()),
                ('born_date', models.TextField()),
                ('garage_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('e_mail', models.TextField()),
                ('address', models.TextField()),
                ('counter_model', models.TextField()),
                ('cuonter_number', models.TextField()),
                ('counter_install_date', models.TextField()),
                ('counter_expluatation_end_date', models.TextField()),
                ('counter_install_start_data', models.IntegerField()),
                ('counter_expluatation_end_data', models.IntegerField()),
            ],
        ),
    ]
