# Generated by Django 3.2.5 on 2021-07-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='e_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
